[tool.poetry]
name = "whisper-speech-recogniniton"
version = "0.1.0"
description = "This project is a transcription service built using FastAPI. It transcribes audio files using the WhisperTranscriber model."
authors = ["Vladimir Katin <katin.v.v@gmail.com>"]
license = "GNU GPL v3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai-whisper = "^20230918"
minio = "7.1.17"
fastapi = "0.103.1"
uvicorn = "0.23.2"
pydantic = "2.4.1"
python-dotenv = "1.0.0"
llvmlite = "^0.41.0"
numba = "^0.58.0"
torch = { version = "2.0.1", source = "torch" }

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.4.2"
httpx = "^0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
