[tool.poetry]
name = "whisper-speech-recogniniton"
version = "0.4.0"
description = "This project is a transcription service built using FastAPI. It transcribes audio files using the WhisperTranscriber model."
authors = ["Vladimir Katin <vladimir.katin.urfu.me>"]
license = "GNU GPL v3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai-whisper = "^20230918"
minio = "7.1.17"
fastapi = "0.104.1"
uvicorn = "0.23.2"
pydantic = "2.4.2"
python-dotenv = "1.0.0"
llvmlite = "^0.41.0"
numba = "^0.58.0"
torch = { version = "2.1.0", source = "torch" }
sqlalchemy = "^2.0.23"
pydub = "^0.25.1"
eyed3 = "^0.9.7"
python-decouple = "^3.8"
librosa = "^0.10.1"
psycopg2-binary = "^2.9.9"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.4.2"
httpx = "^0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
